<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
	<head>
	        <title>Feed The Ducks Productions</title>
	        <link href="/inc/style.css" rel="STYLESHEET" type="text/css" media="screen" />
		<!--[if IE]>
		<link rel="stylesheet" type="text/css" href="/inc/iehacks.css" media="screen"/>
		<![endif]-->
		<link rel="shortcut icon" href="/inc/images/favicon.ico" />
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-185490-13', 'feedtheducksproductions.com');
  ga('send', 'pageview');

  </script>
	</head>
	<body>
		<div id="container">	
			<div id="header">
				<span id="headertext">Feed The Ducks Productions</span>
				<ul>
					<li><a title="Join The Flock" id="flock" href="/jointheflock.shtml">&nbsp;</a></li>
					<li><a title="Contact Us" id="contactus" href="/contactus.shtml">&nbsp;</a></li>
					<li><a title="Productions" id="productions" href="/productions.shtml">&nbsp;</a></li>
					<li><a title="Team" id="team" href="/team.shtml">&nbsp;</a></li>
					<li><a title="About Us" id="aboutus" href="/aboutus.shtml">&nbsp;</a></li>
				</ul>
			</div>
			<div id="content">
